export { default as BannerComponent } from './BannerComponent'
export { default as NavComponent } from './NavComponent'
export { default as SeckillComponent } from './SeckillComponent'
export { default as ProComponent } from './ProComponent'
export { default as HeaderComponent } from './HeaderComponent'